# Generated by Django 2.1.7 on 2019-03-18 02:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('isReply', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('childTweets', models.ManyToManyField(blank=True, related_name='child_tweets', to='mysite.Tweet')),
                ('parentTweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(unique=True)),
                ('avatar', models.TextField(default='/static/images/profile-image.jpg')),
                ('biography', models.TextField(default='')),
                ('birthday', models.TextField(default='')),
                ('location', models.TextField(default='')),
                ('name', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('website', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_by', to='mysite.User')),
                ('following', models.ManyToManyField(blank=True, related_name='follows', to='mysite.User')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='mysite.Tweet')),
                ('lists', models.ManyToManyField(blank=True, related_name='lists', to='mysite.Tweet')),
                ('moments', models.ManyToManyField(blank=True, related_name='moments', to='mysite.Tweet')),
                ('tweets', models.ManyToManyField(blank=True, related_name='tweets', to='mysite.Tweet')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.User'),
        ),
    ]
